export const POKEMONS_FETCH_SUCCESS = "POKEMONS_FETCH_SUCCESS";
export const POKEMONS_TYPE_FETCH_SUCCESS = "POKEMONS_TYPE_FETCH_SUCCESS";
export const SET_DATA_FOR_RENDER = "SET_DATA_FOR_RENDER";
export const SINGLE_POKEMON_FETCH_SUCCESS = "SINGLE_POKEMON_FETCH_SUCCESS";
export const SORT = "SORT";
export const SET_PAGE_LIMIT = "SET_PAGE_LIMIT";
export const SEARCH_POKEMONS = "SEARCH_POKEMONS";
export const CLEAR_SEARCH_POKEMONS = "CLEAR_SEARCH_POKEMONS";
